version: "3.8"
services:
  mongo-db:
    image: mongo:latest
    container_name: "mongodocker"
    ports:
      - 27070:27017
  app:
    build: .
    container_name: "backend-app"
    ports:
      - 5001:5000
    depends_on:
      - mongo-db